'use strict';
const $ = id => document.getElementById(id);
let preferences = null, latest = null, polling = false;
let presetCatalogue = [];
let token = sessionStorage.getItem('aujitter-token') || '';
const number = (n, unit=' ms') => n == null ? '—' : `${n.toFixed(1)}${unit}`;
const date = value => new Date(value).toLocaleString(undefined,{dateStyle:'short',timeStyle:'medium'});
const label = value => ({five_g:'5G',four_g:'4G',nbn_fttp:'NBN FTTP',nbn_fttn:'NBN FTTN',nbn_fttc:'NBN FTTC',nbn_hfc:'NBN HFC',unknown:'Unknown',stable:'Stable',watch:'Watch',degraded:'Degraded',offline:'Offline'})[value] || value.replaceAll('_',' ');
const presetName = value => presetCatalogue.find(item=>item.id===value)?.name || (value==='custom'?'Custom':label(value));
function error(message){$('error').textContent=message;$('error').hidden=!message;}
async function api(path,payload){
  const response=await fetch(`/api/${path}`,{headers:{...(payload?{'Content-Type':'application/json'}:{}),...(token?{'Authorization':`Bearer ${token}`}:{})},...(payload?{method:'POST',body:JSON.stringify(payload)}:{})});
  if(response.status===401){$('login').hidden=false;throw new Error('An access token is required to view this monitor.');}
  if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||`Monitor returned ${response.status}`);}return response;
}
function cell(value,state){const td=document.createElement('td');td.textContent=value;if(state)td.dataset.state=state;return td;}
function list(target,items){target.replaceChildren(...items.map(value=>{const li=document.createElement('li');li.textContent=value;return li;}));}
function graph(rows){
  const svg=$('chart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();
  const node=(tag,attributes,text)=>{const el=document.createElementNS(ns,tag);for(const[key,value]of Object.entries(attributes))el.setAttribute(key,String(value));if(text)el.textContent=text;svg.append(el);return el;};
  const echo=row=>row.probes.find(p=>p.kind==='gateway_icmp')?.latency_ms;
  const values=rows.flatMap(row=>[row.metrics.latency_ms,echo(row)]).filter(value=>value!=null);const maximum=Math.max(100,...values)*1.12;
  for(let i=0;i<5;i++){const y=10+i*48;node('line',{x1:52,y1:y,x2:995,y2:y,class:'grid'});node('text',{x:0,y:y+4},`${Math.round(maximum*(1-i/4))}`);}
  if(!rows.length)return;
  const start=new Date(rows[0].at).getTime(),end=new Date(rows.at(-1).at).getTime();const x=row=>52+(new Date(row.at).getTime()-start)/Math.max(1,end-start)*943;
  for(const[kind,read]of[['internet',row=>row.metrics.latency_ms],['gateway',echo]]){let points=[];const flush=()=>{if(points.length)node('polyline',{points:points.join(' '),class:kind});points=[];};for(const row of rows){const value=read(row);if(value==null||row.observation_gap_seconds!=null){flush();if(kind==='internet')node('circle',{cx:x(row),cy:211,r:3});if(value==null)continue;}points.push(`${x(row)},${202-value/maximum*192}`);}flush();}
  $('chart-start').textContent=date(rows[0].at);$('chart-end').textContent=date(rows.at(-1).at);$('chart-description').textContent=`${rows.length} observations. Timed replies: ${values.length?`${Math.min(...values).toFixed(1)}–${Math.max(...values).toFixed(1)} ms`:'unavailable'}. Gaps show missing replies or unobserved time. Values are in the table below.`;
}
function render(view){
  latest=view;$('version').textContent=view.version;$('gaming').setAttribute('aria-pressed',String(view.gaming));$('pause').textContent=view.paused?'Resume monitoring':'Pause monitoring';$('profile').textContent=`${view.preset==='automatic'?'Automatic → ':''}${presetName(view.effective_preset)} · every ${view.interval_ms/1000}s${view.gaming?' · Gaming mode':''}`;
  for(const id of['preset-reason','automatic-selection']){$(id).textContent=view.preset_reason||'';$(id).hidden=!view.preset_reason;}
  const sample=view.latest;$('state').textContent=view.paused?'Paused':sample?label(sample.diagnosis.severity):'Collecting evidence';document.querySelector('.summary').dataset.severity=view.paused?'unknown':sample?.diagnosis.severity||'unknown';if(!sample)return;
  $('explanation').textContent=view.paused?'No probes are being sent. Resume monitoring to collect new observations.':sample.diagnosis.explanation;$('confidence').textContent=`Confidence: ${sample.diagnosis.confidence}`;$('last-seen').textContent=`Last observation ${date(sample.at)}`;
  $('latency').textContent=number(sample.metrics.latency_ms);$('jitter').textContent=number(sample.metrics.jitter_ms);$('loss').textContent=number(sample.metrics.icmp_loss_percent,'%');const observed=view.hourly.reduce((sum,row)=>sum+row.samples,0),unstable=view.hourly.reduce((sum,row)=>sum+row.unstable_samples,0);$('unstable').textContent=observed?`${(100*unstable/observed).toFixed(1)}%`:'—';
  $('area').textContent=label(sample.diagnosis.area);list($('evidence'),sample.diagnosis.evidence);const steps=document.createElement('ul');list(steps,sample.diagnosis.next_steps);$('steps').replaceChildren();if(sample.diagnosis.next_steps.length){const heading=document.createElement('h2');heading.textContent='What to check next';$('steps').append(heading,steps);}
  const topology=sample.topology;$('topology').replaceChildren();for(const[key,value]of[['ISP',topology.isp||'Not configured'],['Local connection',topology.local_transport],['Interface',topology.interface||'Unavailable'],['Gateway',topology.gateway||'Unavailable'],['DNS resolver',topology.dns_server||'Unavailable'],['WAN type',label(topology.access_type)],['Router',topology.router_model||'Not discovered']]){const dt=document.createElement('dt');dt.textContent=key;const dd=document.createElement('dd');dd.textContent=value;$('topology').append(dt,dd);}$('network-notes').textContent=[topology.access_evidence,...topology.notes].join(' ');graph(view.recent);
  $('samples').replaceChildren(...view.recent.slice(-20).reverse().map(row=>{const tr=document.createElement('tr');tr.append(cell(date(row.at)),cell(label(row.diagnosis.severity),row.diagnosis.severity),cell(number(row.metrics.latency_ms)),cell(number(row.probes.find(p=>p.kind==='gateway_icmp')?.latency_ms)),cell(label(row.diagnosis.area)));return tr;}));
  $('incidents').replaceChildren(...view.incidents.map(row=>{const tr=document.createElement('tr');tr.append(cell(date(row.started_at)),cell(row.ended_at?`${date(row.ended_at)} · ${row.end_reason}`:'Ongoing'),cell(label(row.peak_severity),row.peak_severity),cell(label(row.diagnosis.area)),cell(String(row.unstable_samples)));return tr;}));if(!view.incidents.length){const tr=document.createElement('tr'),td=cell('No incidents recorded yet. The first unstable observation will be logged.');td.colSpan=5;tr.append(td);$('incidents').append(tr);}
}
async function poll(){if(polling||document.hidden)return;polling=true;try{if(!presetCatalogue.length)presetCatalogue=await(await api('presets')).json();render(await(await api('dashboard')).json());$('login').hidden=true;error('');}catch(e){error(`${e.message} Last observations may be stale.`);}finally{polling=false;}}
function describePreset(){const info=presetCatalogue.find(item=>item.id===$('preset-choice').value);$('preset-description').textContent=info?(info.id==='automatic'?info.description:`${info.description} Timeout: ${info.timeout_ms} ms. Warnings: latency ${info.latency_warning_ms} ms; jitter ${info.jitter_warning_ms} ms.`):'Choose a built-in situation to replace custom timing and warning preferences.';}
async function loadPreferences(){preferences=await(await api('settings')).json();const form=$('settings-form');for(const key of['isp','gateway','dns_server','access_type','latency_warning_ms','jitter_warning_ms'])form.elements[key].value=preferences[key]??'';form.elements.interval.value=preferences.interval_ms/1000;form.elements.gaming_interval.value=preferences.gaming_interval_ms/1000;form.elements.discover_router.checked=preferences.discover_router;if(!presetCatalogue.length)presetCatalogue=await(await api('presets')).json();if(!$('preset-choice').options.length){$('preset-choice').replaceChildren(...presetCatalogue.map(item=>new Option(item.name,item.id)));const custom=new Option('Custom preferences','custom');custom.disabled=true;$('preset-choice').append(custom);}$('preset-choice').value=preferences.preset||'automatic';$('active-preset').textContent=`Active preset: ${presetName(preferences.preset)}`;describePreset();}
$('preset-choice').addEventListener('change',describePreset);
$('preset-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{await api('preset',{preset:$('preset-choice').value});await loadPreferences();await poll();$('preset-status').textContent='Preset applied';}catch(e){$('preset-status').textContent=e.message;}finally{button.disabled=false;}});
document.querySelectorAll('.nav').forEach(button=>button.addEventListener('click',async()=>{for(const page of document.querySelectorAll('.page'))page.hidden=page.id!==button.dataset.page;for(const nav of document.querySelectorAll('.nav')){nav.classList.toggle('selected',nav===button);if(nav===button)nav.setAttribute('aria-current','page');else nav.removeAttribute('aria-current');}$('page-title').textContent=button.textContent;if(button.dataset.page==='settings')try{await loadPreferences();}catch(e){error(e.message);}}));
async function command(button,payload){button.disabled=true;try{await api('control',payload);await poll();}catch(e){error(e.message);}finally{button.disabled=false;}}
$('gaming').addEventListener('click',()=>command($('gaming'),{gaming:!latest?.gaming}));$('pause').addEventListener('click',()=>command($('pause'),{paused:!latest?.paused}));
$('settings-form').addEventListener('submit',async event=>{event.preventDefault();if(!preferences)return;const form=event.currentTarget,button=form.querySelector('button[type=submit]');button.disabled=true;$('save-status').textContent='Saving…';try{const next={...preferences};next.gaming=latest?.gaming??preferences.gaming;next.paused=latest?.paused??preferences.paused;for(const key of['isp','gateway','dns_server'])next[key]=form.elements[key].value.trim()||null;next.access_type=form.elements.access_type.value;next.interval_ms=Number(form.elements.interval.value)*1000;next.gaming_interval_ms=Number(form.elements.gaming_interval.value)*1000;next.latency_warning_ms=Number(form.elements.latency_warning_ms.value);next.jitter_warning_ms=Number(form.elements.jitter_warning_ms.value);next.discover_router=form.elements.discover_router.checked;await api('settings',next);await loadPreferences();$('save-status').textContent='Preferences saved';await poll();}catch(e){$('save-status').textContent=e.message;}finally{button.disabled=false;}});
$('export').addEventListener('click',async()=>{try{const blob=await(await api('export')).blob(),link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download='aujitter-evidence.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error(e.message);}});
$('login-form').addEventListener('submit',event=>{event.preventDefault();token=$('token').value;sessionStorage.setItem('aujitter-token',token);poll();});
let light=localStorage.getItem('aujitter-theme')==='light';function applyTheme(){document.documentElement.dataset.theme=light?'light':'dark';$('theme').textContent=light?'Dark theme':'Light theme';}applyTheme();$('theme').addEventListener('click',()=>{light=!light;localStorage.setItem('aujitter-theme',light?'light':'dark');applyTheme();});document.addEventListener('visibilitychange',poll);setInterval(poll,5000);poll();
